### ISSUE TITLE
Pool finder issue when filtering pools

### ISSUE THREAD

**Issue by owodunni** [owodunni/arbie#51]
root        : INFO     Filtering contract 20124 of 20127
root        : INFO     Filtering contract 20125 of 20127
root        : INFO     Filtering contract 20126 of 20127
root        : INFO     Filtering contract 0 of 2237
root        : INFO     Filtering contract 1 of 2237
root        : INFO     Filtering contract 2 of 2237
root        : INFO     Filtering contract 3 of 2237
root        : INFO     Filtering contract 4 of 2237
root        : INFO     Filtering contract 5 of 2237
root        : INFO     Filtering contract 6 of 2237
root        : INFO     Filtering contract 7 of 2237
root        : INFO     Filtering contract 8 of 2237
root        : INFO     Filtering contract 9 of 2237
root        : INFO     Filtering contract 10 of 2237
root        : INFO     Filtering contract 11 of 2237
root        : INFO     Filtering contract 12 of 2237
Traceback (most recent call last):
  File "/home/owodunni/.local/venv/bin/Arbie", line 8, in <module>
    sys.exit(main())
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/__main__.py", line 41, in main
    app.run()
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/arbie.py", line 30, in run
    self.action_tree.run()
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/Actions/action_tree.py", line 47, in run
    action.on_next(data)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/Actions/pool_finder.py", line 87, in on_next
    ) + create_and_filter_pools(balancer_pools, tokens)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/Actions/pool_finder.py", line 49, in create_and_filter_pools
    pool = contract.create_pool()
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/Contracts/pool_contract.py", line 29, in create_pool
    return Pool(tokens, balances, self.get_weights(), self.get_fee())
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/Arbie/Variables/pool.py", line 39, in __init__
    raise ValueError("Weights are not normalized")
ValueError: Weights are not normalized
(venv) [arbie]

**Comment by owodunni** [comment]
More errors:

```
ot        : INFO     Filtering contract 1896 of 2246
root        : INFO     Filtering contract 1897 of 2246
root        : WARNING  Failed to create pool, bad pool. Pool: <bound method Contract.get_address of <Arbie.Contracts.balancer.BalancerPool object at 0x7ff1a53e70a0>>, weights 0.9999999999999999 != 1
root        : INFO     Filtering contract 1898 of 2246
root        : WARNING  Failed to create pool, bad pool. Pool: <bound method Contract.get_address of <Arbie.Contracts.balancer.BalancerPool object at 0x7ff1a53aab80>>, weights 1.0000000000000002 != 1
root        : INFO     Filtering contract 1899 of 2246
root        : INFO     Filtering contract 1900 of 2246
root        : INFO     Filtering contract 1901 of 2246

```

**Comment by owodunni** [comment]
Failed to serialize store:

```
root        : WARNING  Failed to create pool, bad pool. Pool: <bound method Contract.get_address of <Arbie.Contracts.balancer.BalancerPool object at 0x7ff19be7f250>>, has insufficient tokens: 1
root        : INFO     Filtering contract 2244 of 2246
root        : INFO     Filtering contract 2245 of 2246
Traceback (most recent call last):
  File "/home/owodunni/.local/venv/bin/Arbie", line 11, in <module>
    load_entry_point('Arbie', 'console_scripts', 'Arbie')()
  File "/home/owodunni/Prog/arbie/Arbie/__main__.py", line 41, in main
    app.run()
  File "/home/owodunni/Prog/arbie/Arbie/arbie.py", line 33, in run
    pickle.dump(self.store, open(path, "wb"))
AttributeError: Can't pickle local object 'construct_web3_formatting_middleware.<locals>.formatter_middleware'

```
